Fix: ruleResult result removal
frmscoe/rule-901 pull request #27
Opened 2024-05-22 09:24 UTC by cshezi

Related to

2024-05-23 20:08 UTC, Justus-at-Tazama requested changes

2024-05-23 20:08 UTC, Justus-at-Tazama commented on README.md
This readme seems older than the one in https://github.com/frmscoe/rule-901/pull/26

2024-05-24 06:40 UTC, Sandy-at-Tazama approved these changes

2024-05-24 06:55 UTC, JeanPierreNell approved these changes
LGTM

2024-05-24 14:22 UTC, Justus-at-Tazama approved these changes
Approved readme

2024-05-24 14:23 UTC, merged